version: '3.8'

services:
  # Java Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: inventory-backend
    ports:
      - "4567:4567"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - ./challenge.db:/app/challenge.db
    networks:
      - inventory-network
    restart: unless-stopped
    # Simplified health check - just check if container is running
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Next.js Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4567
    # Remove dependency condition to allow frontend to start
    depends_on:
      - backend
    networks:
      - inventory-network
    restart: unless-stopped
    # Simplified health check
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  inventory-network:
    driver: bridge

volumes:
  database:
    driver: local
